### ISSUE TITLE
Question about position encoding

### ISSUE THREAD

**Issue by YangHai-1218** [dingdingcai/SC6D-pose#3]
Hey, it's an interesting work! 
I notice that you have not implemented position encoding for SO3 rotation input, while it has been done in Implicit-PDF. I am wondering if there are any concerns with implementing position encoding.
Thanks!

**Comment by dingdingcai** [comment]
Thanks for your interest in our work! In our work, we use MLP to directly encode a flattened rotation vector into a  representation vector sharing the same length as the image feature vector, where the MLP can already incorporate the position (order) information of the rotation vector into the representation. There is no significant difference in our experiments when including the rotation position embedding.
