### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by yuellong** [dingdingcai/SC6D-pose#6]
Thanks for sharing this great code repo! We found your work interesting and inspiring and we would like to follow up. However, it seems that there's no license associated with it which makes it difficult for us to include any code snippets from you. According to GitHub's help page:

`You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.`

Could you please add an appropriate license if possible? We will give acknowledgements and citations. FYI, this instruction may be helpful: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository. A less restrictive license like Apache-2.0 or MIT would be preferred and appreciated by us. Thanks!

**Comment by dingdingcai** [comment]
Thanks, I've added the license.
